version: '3.7'

services:
  node-graphql:
    container_name: test-app
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    environment:
      - SERVER_PORT=${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/usr/src/app:cached
    command: yarn start:dev
    env_file:
      - .env
    networks:
      - webnet

  db-postgres:
    container_name: db-postgres
    restart: always
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PG_DATA: ./var/lib/postgresql/data
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    env_file:
      - .env
    networks:
      - webnet

networks:
  webnet:

volumes:
  pgdata: